<?php
	require_once("config.php");
	require_once("_app/login.php");	
	require_once("_app/database.php");
	require_once("_app/allposts.php");
    require_once("_app/category.php");
	require_once("_app/post.php");
	require_once("_app/author.php");
?>